/* eslint-disable @next/next/no-sync-scripts */
import Footer from "@/components/Footer/Footer";
import Headers from "@/components/Headers/Headers";
import ReportContent from "@/components/ReportContent/ReportContent";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Daily Report Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <section className="w-full max-w-6xl m-auto ">
        <Headers />
        <ReportContent />
        <Footer />
      </section>
    </>
  );
}
